### PR TITLE
Pull request to introduce copy and paste for GNOME environments and terminal operations.

### LINKED ISSUE #3: Copy&Paste is not supported on Linux yet
This needs to be fixed, but I currently only develop on OS X. Any help would be appreciated.

Cheers

### PR DESCRIPTION
**Pull request by ghost**
Pull request to resolve #3 for GNOME environments.

Also put in some basic terminal interaction, allowing users to run terminal commands without leaving e entirely. Can be used tested by entering meta and then typing - followed by desktop command to run (i.e. "-echo hello" or "-rm -rf X"). This is very basic at the moment.

### CODE REVIEW

**Comment by hellerve** [comment]
I would like to leave the latter part (the terminal commands) out. It’s brittle, and entirely possible from Lua (take a look at my [personal config](https://github.com/hellerve/.dotfiles/blob/master/erc#L27) where I bound this to the `!` key for an example).

**Comment by ghost** [comment]
Understood, I apologise for not noticing that! Reverts have been made.

**Comment by hellerve** [comment]
That’s completely fine! In general, I’d rather that we open one PR per feature instead of putting multiple features in a branch. Maybe I should write a `Contributing` document?

**Comment by hellerve** [comment]
Looks good to me now!

**Comment by ghost** [comment]
@hellerve, that would be cool with me. I understand completely, I'll keep it all separate from now on.

**Pull request merged**
