### PR TITLE
Added execinfo to allow *BSD based systems to make use of backtrace.

### PR DESCRIPTION
**Pull request by ghost**
This shouldn't affect other OS. execinfo is a ported library coming from Linux so anywhere with gcc can use it without hassle, as it is available on Linux based systems by default.

### CODE REVIEW

**Comment by hellerve** [comment]
It seems that I can’t compile it on OS X anymore when this linker flag is added (neither with Clang nor with GCC 7).

Also, OS X is supposed to be a BSD, and seems to be able to get the backtrack just fine. Which BSDs need this (so I can test it if possible)?

**Comment by ghost** [comment]
FreeBSD 11.1, very strange; OS X was perfectly happy with it for me (I ran it on macOS but not Windows). Must be some system taint left over from something else I did.

Out of interest, what is OS X telling you is wrong?

**Comment by ghost** [comment]
If it causes issues I'll just strap the flag into the port file for my FreeBSD port, just means that anyone wanting to use _e_ will need to manually download the code, edit the makefile and build it using gmake, if they want bleeding edge, as opposed to just letting the ports system download the latest release version and install for them.

**Comment by hellerve** [comment]
It cannot find the library. I’m running OS X 11.6, but I’m not sure that’s where the problem lies:

```
mkdir -p /Users/veitheller/.estx
cp stx/* /Users/veitheller/.estx
mkdir -p bin/
gcc-7 main.c src/buffer.c src/clipboard.c src/colors.c src/editor.c src/syntax.c src/util.c -DSTXDIR=\"/Users/veitheller/.estx\" -o bin/e -lexecinfo -Werror -Wall -g -fPIC -O2 -DNDEBUG -ftrapv -Wfloat-equal -Wundef -Wwrite-strings -Wuninitialized -pedantic -std=c11
ld: library not found for -lexecinfo
collect2: error: ld returned 1 exit status
make: *** [all] Error 1
```

**Comment by ghost** [comment]
I am finding it rather odd that gcc is complaining about it, just ran it on Linux (Ubuntu 16.04) and it was fine with it; though I am still not prepared to rule out some system taint on my level. Assuming clean built systems, it must be a conflict between FreeBSD and Linux/MacOS/Windows; I'll close this pull request for now and do some further scrubbing for details later this evening.

**Comment by ghost** [comment]
I think I've got a solution, but won't be able to properly test it out till later tonight.

**Comment by hellerve** [comment]
Take your time, we’re not on a schedule here. ;)

**Comment by ghost** [comment]
I'll try but I want it making coffee by week's end :joy:

**Pull request closed without merging**
