### PR TITLE
Updated Makefile behavior to accomodate *BSD execinfo library require…

### PR DESCRIPTION
**Pull request by ghost**
This should hopefully work  to fix the weird issue on the FreeBSD (as well as OpenBSD and NetBSD) regarding backtrace and execinfo.

I've tested this on FreeBSD 11.1, Ubuntu 16.04 and macOS 10.12.6 (all clean systems). Let me know!

### CODE REVIEW

**Comment by hellerve** [comment]
Why did you close this?

**Comment by ghost** [comment]
Accidental (I went into zombie mode). I meant to push an update to my branch instead. Sorry about that!

**Comment by hellerve** [comment]
Looks good to me now and works on OS X. Could you maybe remove the commented code and then we can merge?

**Comment by ghost** [comment]
Done and done. Apologies, let my testing style shine right through with that comment :joy:

**Comment by hellerve** [comment]
Thank you :+1:

**Pull request merged**
